### ISSUE TITLE
UserService Function AddIDPLink Error

### ISSUE THREAD

**Issue by bman46** [smartive/zitadel-net#700]
When using the AddIDPLink() function, I receive the following error:
```
Grpc.Core.RpcException: Status(StatusCode="Cancelled", Detail="Bad gRPC response. Invalid content-type value: text/html; charset=utf-8")
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequestrequest)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequestrequest)
   at Zitadel.User.V2Alpha.UserService.UserServiceClient.AddIDPLink(AddIDPLinkRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
   at project.Services.SSO.Implementations.Zitadel.GRPCClient.LinkUserIDP(String zitadelUserId, User user) in ...
```
I think this was caused by a change in the latest release of Zitadel as this function has previously worked in my code.

**Comment by buehler** [comment]
Is this still an issue or did it resolve while updating?

**Comment by bman46** [comment]
It was resolved with an update. Thanks!
