### ISSUE TITLE
Problem when not using HTTPS

### ISSUE THREAD

**Issue by DerStimmler** [smartive/zitadel-net#785]
Hi, currently I'm hosting a test instance of zitadel in docker. The address is `http://localhost:8080`.

Now I want to access the zitadel api via a `ManagementClient` of this library.

```csharp
    var serviceAccount = ServiceAccount.LoadFromJsonString(serviceAccountJson);
    _managementClient = Clients.ManagementService(new Clients.Options(options.Value.Authority, ITokenProvider.ServiceAccount(options.Value.Authority, serviceAccount, new ServiceAccount.AuthOptions { ApiAccess = true })));

...

    var usersResponse = await _managementClient.ListUsersAsync(new ListUsersRequest());
```

However when I use this client I get the following exception:

```csharp
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. InvalidOperationException: IDX20803: Unable to obtain configuration from: 'http://localhost:8080/.well-known/openid-configuration'. ArgumentException: IDX20108: The address specified 'http://localhost:8080/.well-known/openid-configuration' is not valid as per HTTPS scheme. Please specify an https address for security reasons. If you want to test with http address, set the RequireHttps property  on IDocumentRetriever to false. (Parameter 'address')", DebugException="System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'http://localhost:8080/.well-known/openid-configuration'.")
 ---> System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'http://localhost:8080/.well-known/openid-configuration'.
 ---> System.ArgumentException: IDX20108: The address specified 'http://localhost:8080/.well-known/openid-configuration' is not valid as per HTTPS scheme. Please specify an https address for security reasons. If you want to test with http address, set the RequireHttps property  on IDocumentRetriever to false. (Parameter 'address')
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync()
   at Zitadel.Credentials.ServiceAccount.AuthenticateAsync(String audience, AuthOptions authOptions)
   at Zitadel.Api.ServiceAccountTokenProvider.Handler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
   --- End of inner exception stack trace ---
```

I think it's related to gRPC and the need for HTTPS but I can't find a way to set `RequireHttps` on `IDocumentRetriever` to `false` as mentioned in the error.

I've already tried to resolve the issue by calling the following code as described in the Microsoft documentation on gRPC but no improvement:

```csharp
IdentityModelEventSource.ShowPII = true;
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
```

Is it possible that this library can't be used without HTTPS or is there a way to work around this?

**Comment by buehler** [comment]
Hey @DerStimmler 

I have not used it without HTTPS. You can try to create the client by yourself.
The logic where the cliens are created can be found here: https://github.com/smartive/zitadel-net/blob/main/src/Zitadel/Api/Clients.cs#L39-L64

You can pass your own "GrpcChannel" options and specify "insecure channel" there. There is a way to create insecure connections in the GrpcChannels.

Hope this helps :-)

**Comment by DerStimmler** [comment]
@buehler thanks for your help. I've switched to HTTPS as well, but I might give it a try to use an insecure channel.

**Comment by grimurd** [comment]
Any plans to support regular http? While it's not difficult to create a custom client it should be supported for those of us running zitadel locally during development.

**Comment by Benjamin23** [comment]
Hi @buehler , can someone please review the PR form @grimurd ? I got the same problems while developing locally, and I'm currently working with a locally patched version with his fix
